### ISSUE TITLE
Support Pydantic natively

### ISSUE THREAD

**Issue by diogobaeder** [coherent-oss/python-kustomize#10]
We should start supporting Pydantic models natively as sources for generating Kustomize YAML.

Since this tool is usually tracked as a deployment time dependency, I think there's no need to support Pydantic 1, and could go straight for Pydantic 2. I'm open to be convinced of the contrary though.

**Comment by bswck** [comment]
I'm very opposed to supporting Pydantic 1.
Pydantic wrote an [entire transformation tool](https://docs.pydantic.dev/latest/migration/#code-transformation-tool) so that people use v2.

**Comment by diogobaeder** [comment]
Implemented. Will be released soon.
