### ISSUE TITLE
Configure automatic release of tagged versions

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/python-kustomize#3]
This project, like other skeleton-based projects are already configured with a GitHub workflow to automatically release tagged commits. This release flow requires configuration of the PYPI_TOKEN in the project (and that token has to be authorized to publish to the project in PyPI).

As currently configured, this release flow is going to fail because that token doesn't exist. We'll probably want to fix that.

Eventually, I'd like to configure coherent-oss projects to use "trusted publishers" to publish projects without the need for a PYPI_TOKEN, but I've resisted doing that until there's some way to [automate the process](https://github.com/pypi/pypi-oidc-private-beta-community/issues/34). That said, if this project is interested in becoming the guinea pig, we could enable it as the first project to adopt trusted publishers and see what that implies for the configuration.

Alternatively, if we're going with the status quo, we could configure PYPI_TOKEN in this project, either using one generated by the current maintainer/owner (@diogobaeder) or by adding @jaraco as a maintainer/owner of the project in PyPI and installing my token to this project.

A third and final option could be to leave the automatic releases broken and rely on manual releases (`tox -e release`). That would be manageable but undesirable as all of those release jobs will fail, leaving the actions page littered with expected failing jobs and tempting us to remove the automatic release process.

Diogo, how would you like to proceed?

**Comment by diogobaeder** [comment]
I think the idea of having "trusted publishers" sounds good to me - the reason why I wanted to host this project in this organization was so that I could democratize it and share the ownership with others, so it seems to go in that direction. I'm happy to make this project a guinea pig - it's not super popular yet, and there's a working package version in PyPI already, so all good!

**Comment by jaraco** [comment]
Done in #8.
