### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/python-kustomize#4]
This project should cut a new release to update the metadata in the released project.

I'll illustrate how releases are done under the skeleton design:

- [x] Add any changelog entries that might be missing (using towncrier).
- [x] Make it a patch version #9.
- [x] Consider adding other maintainers.
- [x] Get an updated email for Diogo.
- [x] Ensure automated releases are properly configured (one time) #3.
- [x] Run `tox -e finalize`, possibly review the commit, then push (with tags).

**Comment by diogobaeder** [comment]
I'm not sure changing the release process justifies a new library release. But I do want to implement a new feature, which is direct support to Pydantic models; So how about we implement this feature first, and then cut a release following this new process?

**Comment by jaraco** [comment]
I'm fine with that. The things that would change with the release are the hyperlinks from PyPI and other changes like supported Python version. In my opinion, frequent releases is better (easier to bisect), but if we are talking weeks and not months, I'm fine waiting. Also, it's your project and your call.

**Comment by jaraco** [comment]
Oh, I should mention too, it would be easier to configure and validate the release process now while the changes are fresh in my mind, and then do an easy, mindless release next time with real features.

**Comment by diogobaeder** [comment]
@jaraco alright, I'm sold! Feel free to release it at any point.

Also, feel free to put your name - or maybe replace mine with Coherent OSS. I don't mind sharing ownership and authorship with the group as a whole :-)

**Comment by diogobaeder** [comment]
Suggestion: release a patch version.

**Comment by jaraco** [comment]
Note how the version that gets released is automatically computed based on the changes described in `newsfragments`. If there's nothing but `bugfix`es, a `patch` bump will be created. If there are `feature`s, a minor release will be created, and if there are `removal`s, a major bump will occur.

I considered adding Coherent OSS or myself to the authors or maintainers, but I'm not interested in having my name on it and I'm not yet well-versed in adding an organization as a maintainer or author, so let's leave Diogo as the author.

I noticed that the email for Diogo is old; is there a better one to use?

**Comment by diogobaeder** [comment]
Oh, I didn't know that, thanks for the hint! I'm still pretty much ignorant in `towncrier`, but I'll definitely read more about how it works.

Indeed, the old org e-mail is still there, sorry; Can you use diogobaeder@yahoo.com.br please?

**Comment by jaraco** [comment]
Okay. #9 is merged. Last step is to run `finalize` and push:

```
 python-kustomize main @ git-id
05888b4
 python-kustomize main @ tox -e finalize
finalize: install_deps> python -I -m pip install 'jaraco.develop>=7.23' towncrier
finalize: commands[0]> python -m jaraco.develop.finalize
Loading template...
/Users/jaraco/code/coherent-oss/python-kustomize/.tox/finalize/lib/python3.12/site-packages/towncrier/build.py:169: EncodingWarning: 'encoding' argument not specified
  resources.files(config.template[0]).joinpath(config.template[1]).read_text()
Finding news fragments...
Rendering news fragments...
Writing to newsfile...
Staging newsfile...
Removing the following files:
/Users/jaraco/code/coherent-oss/python-kustomize/newsfragments/1.bugfix.rst
/Users/jaraco/code/coherent-oss/python-kustomize/newsfragments/+c4121634.bugfix.rst
Removing news fragments...
Done!
[main 7c4e728] Finalize
 3 files changed, 10 insertions(+), 2 deletions(-)
 delete mode 100644 newsfragments/+c4121634.bugfix.rst
 delete mode 100644 newsfragments/1.bugfix.rst
  finalize: OK (6.13=setup[5.51]+cmd[0.62] seconds)
  congratulations :) (6.19 seconds)
 python-kustomize main @ git diff HEAD~1
diff --git a/NEWS.rst b/NEWS.rst
index 8ec8369..511da93 100644
--- a/NEWS.rst
+++ b/NEWS.rst
@@ -1,3 +1,13 @@
+v0.5.1
+======
+
+Bugfixes
+--------
+
+- Refreshed the package metadata. (#1)
+- Require Python 3.8 or later.
+
+
 0.5.0
 =====
 
diff --git a/newsfragments/+c4121634.bugfix.rst b/newsfragments/+c4121634.bugfix.rst
deleted file mode 100644
index 37ecfae..0000000
--- a/newsfragments/+c4121634.bugfix.rst
+++ /dev/null
@@ -1 +0,0 @@
-Require Python 3.8 or later.
\ No newline at end of file
diff --git a/newsfragments/1.bugfix.rst b/newsfragments/1.bugfix.rst
deleted file mode 100644
index 7364bf2..0000000
--- a/newsfragments/1.bugfix.rst
+++ /dev/null
@@ -1 +0,0 @@
-Refreshed the package metadata.
\ No newline at end of file
 python-kustomize main @ git push
Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.76 KiB | 1.76 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/coherent-oss/python-kustomize
   05888b4..7c4e728  main -> main
 * [new tag]         v0.5.1 -> v0.5.1
```

Let's see how that goes.

**Comment by jaraco** [comment]
Oh, shoot. There's a bug in the workflow file.

![image](https://github.com/coherent-oss/python-kustomize/assets/308610/4f67a8f8-3cbe-4d57-8a90-6b1f7a8c9a27)

I must have missed that in #8. That's annoying - that the "permissions" needs to be consolidated and so can't keep "trusted publishing" concerns grouped together.

**Comment by jaraco** [comment]
Since the automated build failed, I recovered thus:

- deleted the tag (locally and in remote)
- repaired the workflow (a26b30c)
- manually re-tagged and pushed with `git tag -a -m "" v0.5.1`; git push`

**Comment by jaraco** [comment]
[Success](https://pypi.org/project/kustomize/0.5.1/)

**Comment by diogobaeder** [comment]
Nice! Let's see how we can update the Python versions badge now... hahahaha
