### ISSUE TITLE
Consider renaming this project in GitHub

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/python-kustomize#5]
I've found it's often desirable to have a project's name match its name in GitHub and PyPI. In fact, I have aspirations to create a zero-config design that would rely on the GitHub repo name indicating the project name.

Is there any value in the `python-` prefix here, or could it be renamed to `/coherent-oss/kustomize`? It seems unlikely to me that we'll ever need to disambiguate it from `rust-kustomize` or `java-kustomize` within the `coherent-oss` namespace, no?

**Comment by diogobaeder** [comment]
In general I'd be in favor, but in this case I think it's important to make it clear that it's not a fork of Kustomize itself, but rather a Python library to help building manifests for it. So I see value in the `python-` part. This is also usually true for Rust packages for example, like `foo.rs`, `bar-rs` or such.

**Comment by jaraco** [comment]
Fair enough.
